spring.datasource:
  url: jdbc:mariadb://localhost/OktagonFantaDatabase?createDatabaseIfNotExist=true
  username: root
  password:


server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    mapper:
      accept-case-insensitive-enums: true